import os

SAN_URL = os.environ.get("SAN_URL")
BRIGHTCOVE_ACCOUNT_ID = os.environ.get("BRIGHTCOVE_ACCOUNT_ID")
BRIGHTCOVE_POLICY_KEY = os.environ.get("BRIGHTCOVE_POLICY_KEY")

OTEL_DEPLOYMENT_ENVIRONMENT = os.environ.get("OTEL_DEPLOYMENT_ENVIRONMENT")
OTEL_EXPORTER_OTLP_ENDPOINT = os.environ.get("OTEL_EXPORTER_OTLP_ENDPOINT")
GRAFANA_LABS_TOKEN = os.environ.get("GRAFANA_LABS_TOKEN")
